spring.application.name=hibernate

spring.datasource.url=jdbc:mysql://localhost:3308/biblioteca_db
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Mostra o SQL gerado
spring.jpa.show-sql=true

# Formata o SQL pra ficar legível (sem isso vira uma linha só, ilegível)
spring.jpa.properties.hibernate.format_sql=true

# Mostra os valores reais dos parâmetros (sem isso você só vê "?" no lugar dos valores)
logging.level.org.hibernate.orm.jdbc.bind=trace